In [8]:
import numpy as np

arr = np.zeros(10 , dtype = int)
arr[4] = 1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


In [11]:
a = np.arange(10,50)

print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
a = [1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [18]:
x = np.random.random((10,10))
print(x) 
xmin = x.min()
xmax = x.min()
print("Min value:")
print(xmin)
print('Max Value:')
print(xmax)

[[0.41114552 0.37204628 0.44992144 0.72436565 0.1437462  0.2499119
  0.98767975 0.613736   0.063098   0.29865933]
 [0.77274685 0.46173265 0.82602842 0.40248576 0.57729771 0.19830388
  0.87764727 0.75422108 0.46067799 0.31232895]
 [0.63333998 0.55346244 0.72795745 0.12456838 0.74514311 0.66514395
  0.55793099 0.89723204 0.2660573  0.68328485]
 [0.52509237 0.64356995 0.9510536  0.66306122 0.84009528 0.83587336
  0.29531511 0.97850294 0.46153586 0.16596421]
 [0.41299351 0.6538084  0.1297566  0.05539994 0.72834101 0.56610729
  0.16243481 0.46555343 0.20211196 0.36393324]
 [0.70708656 0.51735237 0.50800854 0.44148052 0.82393766 0.17296965
  0.76872754 0.13077349 0.51255155 0.16654423]
 [0.90964577 0.13305484 0.82836636 0.33125969 0.19978216 0.93287525
  0.86251069 0.25336477 0.86493811 0.19269605]
 [0.85678598 0.20268586 0.30220143 0.16631082 0.81522222 0.63230369
  0.1610163  0.54696736 0.54385041 0.83962686]
 [0.03522371 0.55964273 0.30514832 0.90367936 0.71240009 0.23911006
  0.43070471 

In [27]:
x = np.random.random(30)
print(x)
a = np.mean(x)                              
print("Mean Value: = ",a)

[0.15920753 0.51189135 0.77425304 0.57819084 0.03648667 0.46350744
 0.0362237  0.42444029 0.84117036 0.06111333 0.13064773 0.51445118
 0.08062347 0.41022116 0.81784526 0.91007374 0.63214394 0.13407484
 0.09269063 0.23655246 0.13793985 0.71138609 0.1782687  0.04081186
 0.49246145 0.1243828  0.38969493 0.02213663 0.49879245 0.88190742]
Mean Value: =  0.37745303799827296
